const USER_ROLES_ENUM = ['DYNATON', 'ADVERTISER', 'PUBLISHER', 'CLIENT', 'AGENCY'];
const Status_ENUM = ['PENDING', 'APPROVED', 'REJECTED'];

const CAMPAIGN_STATUS_ENUM = {
    REVIEW : 1,
    REJECTED : 11,
    ACTIVE : 2,
    STOPPED : 3,
    COMPLETED : 4
}

const PAYOUT_STATUS_ENUM = {
    UNPAID : 0,
    PAID : 1,
    PROCESSING  : 2
};

const TRANSACTION_STATUS_ENUM = {
    PAID_TRANSACTION : 2,
    PENDING_TRANSACTION : 1,
    FAILED_TRANSACTION : 0
};

const USER_STATUS_ENUM = {
    NOT_VERIFIED : 1,
    ACTIVE : 2,
    SUSPENDED : 3
}

const MULTI_FA_STATUS_ENUM = {
    DISABLED : 0,
    NOT_VERIFIED: 1,
    ENABLED: 2
}

module.exports = {
    PAYOUT_STATUS_ENUM,
    USER_ROLES_ENUM,
    Status_ENUM,
    TRANSACTION_STATUS_ENUM,
    USER_STATUS_ENUM,
    CAMPAIGN_STATUS_ENUM,
    MULTI_FA_STATUS_ENUM
}
